import "./globals.css";
import "../assets/font/stylesheet.css";

export const metadata = {
  title: "Profile Info UI",
  description: "Generated by AlirezaAbd",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
